### PR TITLE
Mylin/#6 add set region annotation test

### PR DESCRIPTION
**Pull request by acdo2002**
#6 
This is the new added set region annotation test.
It will create a new region ICD and check the response ICD message.
Then export the region file to (image folder path)/set_QA/tmp and then the test will import this region file.
In the final stage, the test deletes the new created region file in (image folder path)/set_QA/tmp

### CODE REVIEW

**Comment by ajm-ska** [comment]
@acdo2002 It works until the last stage:
```
 Command failed: rm /./set_QA/tmp/set_region_annotation_test_pixel.crtf
    rm: cannot remove '/./set_QA/tmp/set_region_annotation_test_pixel.crtf': No such file or directory
```
It seems it does not know the full path. The file is actually at `/images/set_QA/tmp/set_region_annotation_test_pixel.crtf`, although I guess we shouldn't set the absolute path in our case as other people running the ICD tests might have set_QA somewhere else. 

It wrote the file in the correct place without problems. Is it using a different method to determine the path when deleting it?

However, would it be possible to use `/tmp` instead? If there is more than one CI platform running on the same server, they will be sharing the same `/images` folder, and will be trying to create and delete the same copy of the file. If it is `/tmp` then that will be unique to each platform.

**Comment by acdo2002** [comment]
@ajm-asiaa I have set the export/import/delete file path to "/tmp", please check whether it works or not?

**Comment by acdo2002** [comment]
@ajm-asiaa I modify the test code, now the region will export to set_QA/tmp and will not delete it.
If the test re-run again, the new exported file will overwrite the old one.

**Review by ajm-ska — APPROVED** [review]
@acdo2002 The new test passes on all platforms now! 

(Thanks for removing the rm step. I'm sorry, my previous suggestion of using /tmp was bad. I only realised afterwards that the CI runs every carta_backend instance with "base" and "top_level_folder" set to /images, so it would be unable to access the system's /tmp folder. Although I know we could change the CI so that "top_level_folder" is set to "/", assuming it would not interfere with any other ICD tests. But for now the current solution of not doing "rm" is fine).

**Pull request merged**
