### PR TITLE
update the FILEINFO_FITS_MULTIHDU.test.ts for the swapped images

### PR DESCRIPTION
**Pull request by acdo2002**
solve #4 , please test with Mark's backend(mark/1178_set_render_axes_as_0_and_1) and protobuf(mark/add_axes_numbers) branch.

Once it is ok(passed), then leave this PR (**do not merge**) until Adrianna merge Mark's backend into dev, then I will merge this branch to the ICD-RxJS dev.

Have tested with MacOS11(M1) and Ubuntu 22.04

### CODE REVIEW

**Review by ajm-ska — APPROVED** [review]
Tested on AlmaLinux8. Seems fine.

**Comment by acdo2002** [comment]
@ajm-asiaa 
There are new added ICD tests for supporting the swapped images.
OPEN_SWAPPED_IMAGES.test.ts
ANIMATOR_SWAPPED_IMAGES.test.ts
The testing images can be found in [here](https://drive.google.com/drive/u/1/folders/1xJbRMcmq-6ka_WCgUMyiwMcodhQP45fg)
testing images include `HH211_IQU-swap-rfds.image`, `HH211_IQU-swap-rsdf.image`, `HH211_IQU-swap-fdsr.image`, `supermosaic.10-cutted-stokes-glon-vard-glat.image`, and `HH211_IQU-swap-dsrf.image`.

Please test these test codes with Mark's backend(mark/1178_set_render_axes_as_0_and_1) and protobuf(mark/add_axes_numbers) branch.

**Comment by ajm-ska** [comment]
@acdo2002 I have downloaded the new test images and put them on the RHEL8 and macOS12 servers for now. But I'm having some trouble. Am I correct that we should have the following configuration?

- carta-backend: 
  - branch `mark/1178_set_render_axes_as_0_and_1`
  - carta-protobuf branch `mark/add_axes_numbers`

- ICD-RxJS:
  - branch `mylin/#4_update-fits-multihdu`
  - protobuf branch`HEAD detached at aeb52e8`

The `src/test/OPEN_SWAPPED_IMAGES.test.ts` works fine on RHEL8, so I assume I have checked out the correct branches there. But in `FILEINFO_FITS_MULTIHDU.test.ts` I get one error:

>     Expected: "[07:09:13.1081, -010.36.38.5952]"
>     Received: "[07:09:13.1081, +349.23.21.4048]"

Also, the `ANIMATOR_SWAPPED_IMAGES.test.ts` test passes, but the terminal shows one warning:

>   console.warn src/test/ANIMATOR_SWAPPED_IMAGES.test.ts:250
>     (Step 3) Sequent channel index: 1,2,3,4,0,1,2

Although my main problem seems to be on macOS12. I appear to have the same branches checked out but have errors in all the tests suggesting I have the branches wrong. For example, on `src/test/FILEINFO_FITS_MULTIHDU.test.ts` I get:

>     Expected: "[830, 870] (RA, DEC)"
>     Received: "[830, 870] (Right Ascension, Declination)"

Does that indicate that I have the wrong carta-backend branch?

**Comment by acdo2002** [comment]
@ajm-asiaa 
Because now the Mark's branch has been merged into the dev. And I also have update ICD-RxJS protobuf dev.
For the carta-backend, please use the current `dev` branch.
For the ICD-RxJS, please checkout to mylin/#4_update-fits-multihdu (the protobuf is already in dev branch, you don't have to checkout to other branch).
And you can run `FILEINFO_FITS_MULTIHDU.test.ts` directly, in principle, the results should consistent to all the platforms.

If the test is still failed on RHEL8 and MacOS 12,
--Could you put the image into cartaviewer:/images/set_QA? I can test directly with RHEL8.--
**Sorry I found these tests are already there! Thank you Anthony!!!**

About warning message in `ANIMATOR_SWAPPED_IMAGES.test.ts`, you don't have to worry, it is normal, so far all animator tests will warm the running sequence (let tester knows which channels/stokes it has been run), however the warning message will replace by console.log in the future jest version update.

**Comment by ajm-ska** [comment]
@acdo2002 Thank you! Now that I have switched to the carta-backend `dev` branch, the tests are passing on macOS12 and RHEL8. I will proceed to test on the other platforms.

**Review by ajm-ska — APPROVED** [review]
@acdo2002 Thanks for getting around the mysterious issue in OPEN_SWAPPED_IMAGES.test.ts on macOS platforms:

> TypeError: Cannot read properties of undefined (reading 'histograms')

The tests in this PR are passing now.

On Jenkins, I have added OPEN_SWAPPED_IMAGES to the "session and file_browser" stage and ANIMATOR_SWAPPED_IMAGES to the "animator" stage. The modified FILEINFO_FITS_MULTIHDU remains in the "session and file_browser" stage.

**Pull request merged**
